services:
  - type: web
    name: door-fastapi-app
    env: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: python main_render.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: USE_NEON
        value: true
      - key: NEON_HOST
        value: ep-icy-violet-adv1dwix.c-2.us-east-1.aws.neon.tech
      - key: NEON_PORT
        value: 5432
      - key: NEON_DATABASE_NAME
        value: neondb
      - key: NEON_USER
        value: neondb_owner
      - key: NEON_PASSWORD
        value: npg_EntrThk1V8KI
      - key: SECRET_KEY
        value: QkUqe3w0afBLrDIza80p-49-aNsQyOcEQDEw9hCLU4g
      - key: ADMIN_PASSWORD
        value: admin123
    healthCheckPath: /health
    autoDeploy: true
