version: '3.8'

services:
  postgres-mirror:
    container_name: postgres-mirror
    image: postgres:16
    environment:
      POSTGRES_DB: bdoor_postgres
      POSTGRES_USER: bdoor_user
      POSTGRES_PASSWORD: bdoor_password
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_mirror_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - door-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bdoor_user -d bdoor_postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    labels:
      - "com.door.service=postgres"
      - "com.door.environment=mirror"

volumes:
  postgres_mirror_data:
    driver: local

networks:
  door-network:
    driver: bridge
